#Snakefile parameters
query_species: "sarHar1"
genome_path_query: "data/genomes/sarHar1/sarHar1.fa"
target_species_list: ["ThyCyn2.0", "mSarHar1.11", "AStuM", "DasVivv1.0", "mMyrFas1", "mDroGli1"]
working_dir: "output"
target_species_path: "target_species_v2.tsv"
#chromosomes: ["chr1", "chr2", "chr3", "chr4", "chr5", "chr6", "chr7", "chr8", "chr9", "chr10","chr11", "chr12", "chr13", "chr14", "chr15","chr16", "chr17", "chr18", "chr19"]
chromosomes: ["chr19"]

##liftover parameters
chain_file: "data/chain_files/mm10ToSarHar1.over.chain.gz"
minMatch: 0.5
intermediate: "output/liftoff_intermediate"

##liftoff parameters
features: "data/features2.txt" #List of the conserved elements
flank: 0 #flank parameter for initial Liftoff step. 
flank_remap: 1 #flank parameter for the second Liftoff step. 
