name: liftoff_snakemake
channels:
  - bioconda
  - biocore
  - conda-forge
  - defaultsdependencies:  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aioeasywebdav=2.4.0
  - aiohttp=3.9.1
  - aiosignal=1.3.1
  - amply=0.1.6
  - appdirs=1.4.4
  - argcomplete=3.2.1
  - argh=0.31.0
  - async-timeout=4.0.3
  - attmap=0.13.2
  - attrs=23.2.0
  - bcrypt=4.1.2
  - bedops=2.4.41
  - bedtools=2.31.1
  - biopython=1.82
  - bleach=6.1.0
  - boltons=23.1.1
  - boto3=1.34.14
  - botocore=1.34.14
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.24.0
  - ca-certificates=2024.2.2
  - cachetools=5.3.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - cheetah3=3.2.6.post2
  - coin-or-cbc=2.10.10
  - coin-or-cgl=0.60.7
  - coin-or-clp=1.17.8
  - coin-or-osi=0.108.8
  - coin-or-utils=2.11.9
  - coincbc=2.10.10
  - colorama=0.4.6
  - conda=22.11.1
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - configargparse=1.7
  - connection_pool=0.0.3
  - cryptography=41.0.3
  - curl=7.87.0
  - datrie=0.8.2
  - defusedxml=0.7.1
  - docutils=0.20.1
  - dpath=2.1.6
  - dropbox=11.36.2
  - eido=0.2.2
  - exceptiongroup=1.2.0
  - filechunkio=1.8
  - frozenlist=1.4.1
  - ftputil=5.1.0
  - future=0.18.3
  - galaxy-containers=21.9.0
  - galaxy-tool-util=21.9.1
  - galaxy-util=21.9.0
  - gffread=0.12.7
  - gffutils=0.12
  - gitdb=4.0.11
  - gitpython=3.1.40
  - google-api-core=2.15.0
  - google-api-python-client=2.112.0
  - google-auth=2.26.1
  - google-auth-httplib2=0.2.0
  - google-cloud-core=2.4.1
  - google-cloud-storage=2.14.0
  - google-crc32c=1.1.2
  - google-resumable-media=2.7.0
  - googleapis-common-protos=1.62.0
  - grpcio=1.42.0
  - htslib=1.17
  - httplib2=0.22.0
  - humanfriendly=10.0
  - idna=3.6
  - importlib-metadata=7.0.1
  - importlib_resources=6.1.1
  - iniconfig=2.0.0
  - interlap=0.2.7
  - jinja2=3.1.2
  - jmespath=1.0.1
  - jsonschema=4.20.0
  - jsonschema-specifications=2023.12.1
  - jupyter_core=5.7.0
  - k8=0.2.5
  - keyutils=1.6.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libabseil=20230802.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=7.87.0
  - libdeflate=1.13
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.51.0
  - libnsl=2.0.1
  - libopenblas=0.3.25
  - libpng=1.6.39
  - libprotobuf=4.24.4
  - libsodium=1.0.18
  - libsqlite=3.44.2
  - libssh2=1.10.0
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - liftoff=1.6.3
  - logmuse=0.2.6
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - mdurl=0.1.2
  - minimap2=2.26
  - multidict=6.0.4
  - muscle=5.1
  - mysql-connector-c=6.1.11
  - nbformat=5.9.2
  - ncurses=6.4
  - networkx=3.2.1
  - numpy=1.26.3
  - oauth2client=4.1.3
  - openssl=1.1.1w
  - packaging=23.2
  - pandas=2.1.4
  - paramiko=3.4.0
  - parasail-python=1.3.4
  - peppy=0.40.0
  - phast=1.5
  - pip=23.3.2
  - pkgutil-resolve-name=1.3.10
  - plac=1.4.2
  - platformdirs=4.1.0
  - pluggy=1.3.0
  - ply=3.11
  - prettytable=3.9.0
  - protobuf=4.24.4
  - psutil=5.9.7
  - pulp=2.7.0
  - pyasn1=0.5.1
  - pyasn1-modules=0.3.0
  - pycosat=0.6.6
  - pycparser=2.21
  - pyfaidx=0.7.2.2
  - pygments=2.17.2
  - pynacl=1.5.0
  - pyopenssl=23.2.0
  - pyparsing=3.1.1
  - pysam=0.21.0
  - pysftp=0.2.9
  - pysocks=1.7.1
  - pytest=7.4.4
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.1
  - python-irodsclient=1.1.9
  - python-tzdata=2023.4
  - python_abi=3.10
  - pytz=2023.3.post1
  - pyu2f=0.1.5
  - pyvcf3=1.0.3
  - pyyaml=6.0.1
  - readline=8.2
  - referencing=0.32.1
  - repoze.lru=0.7
  - requests=2.31.0
  - reretry=0.11.8
  - rich=13.7.0
  - routes=2.5.1
  - rpds-py=0.16.2
  - rsa=4.9
  - ruamel.yaml=0.17.40
  - ruamel.yaml.clib=0.2.7
  - s3transfer=0.10.0
  - samtools=1.18
  - setuptools=69.0.3
  - setuptools-scm=8.0.4
  - simplejson=3.19.2
  - six=1.16.0
  - slacker=0.14.0
  - smart_open=6.4.0
  - smmap=5.0.0
  - snakemake=7.32.4
  - snakemake-minimal=7.32.4
  - stone=3.3.1
  - stopit=1.1.2
  - tabulate=0.9.0
  - throttler=1.2.2
  - tk=8.6.13
  - tomli=2.0.1
  - toolz=0.12.0
  - toposort=1.10
  - tqdm=4.66.1
  - traitlets=5.14.1
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2023d
  - ubiquerg=0.6.3
  - ucsc-fasplit=377
  - ucsc-liftover=447
  - ucsc-maffrags=377
  - ucsc-mafspeciessubset=377
  - ujson=5.9.0
  - uritemplate=4.1.1
  - urllib3=1.26.18
  - veracitools=0.1.3
  - wcwidth=0.2.12
  - webencodings=0.5.1
  - wheel=0.42.0
  - whoosh=2.7.4
  - wrapt=1.16.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.3
  - yte=1.5.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
    - annotated-types==0.6.0
    - contourpy==1.3.0
    - cycler==0.12.1
    - fonttools==4.54.1
    - galaxy-lib==19.5.2
    - kiwisolver==1.4.7
    - lxml==5.0.1
    - matplotlib==3.9.2
    - pillow==11.0.0
    - pycryptodome==3.19.1
    - pydantic==2.5.3
    - pydantic-core==2.14.6
    - sortedcontainers==2.4.0
    - zipstream-new==1.1.8

